# Generated by Django 4.1.6 on 2023-02-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='imagem',
            field=models.ImageField(null=True, upload_to='produtos'),
        ),
    ]
