# Generated by Django 4.1.6 on 2023-02-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_remove_product_brand_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagem',
            field=models.ImageField(null=True, upload_to='home/images'),
        ),
    ]
