# Generated by Django 4.1.6 on 2023-02-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0004_alter_product_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagem',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
    ]
