# Generated by Django 4.1.6 on 2023-02-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0005_alter_product_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guest_email',
            field=models.CharField(default='Convidado', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='guest_name',
            field=models.CharField(default='Convidado', max_length=100),
        ),
    ]
